### PR TITLE
0.13 branch Revert track_order=True avoiding a bug in h5py

### PR DESCRIPTION
**Pull request by hmaarrfk**
Review after: https://github.com/h5netcdf/h5netcdf/pull/140

- [ ] Closes Issue #xxxx
- [ ] Tests added
- [ ] Changes are documented in `CHANGELOG.rst`

### CODE REVIEW

**Comment by kmuehlbauer** [comment]
@hmaarrfk That looks good to me. Is there anything left from your side? (It's still WIP)

**Comment by kmuehlbauer** [comment]
@hmaarrfk We missed to fix the README.rst, track_order - section.

**Comment by hmaarrfk** [comment]
If the note is ok. i can forward port.

**Comment by hmaarrfk** [comment]
not a WIP, just wanted to flag this as "secondary"

**Comment by kmuehlbauer** [comment]
Thanks Mark!

**Pull request merged**
