### PR TITLE
Include h5pyd.Dataset objects as netCDF variables

### PR DESCRIPTION
**Pull request by ajelenak**
A simple fix to include `h5pyd.Dataset` objects in the list of variables when scanning file content.

### CODE REVIEW

**Comment by kmuehlbauer** [comment]
@ajelenak Thanks. It looks like that's the last missing part of full `h5pyd` compatibility, right? 

We might consider setting up `h5pyd`-testing again. Do you know of any good resources for testing `h5pyd` in github actions CI?

**Comment by ajelenak** [comment]
> It looks like that's the last missing part of full `h5pyd` compatibility, right?

Probably but I did not run the tests to verify.

> We might consider setting up `h5pyd`-testing again. Do you know of any good resources for testing with `h5pyd` in github actions CI?

This turned to be a pain the first time. I will ask around to see if we can improve this time. I agree it would good to have again.

**Comment by kmuehlbauer** [comment]
> This turned to be a pain the first time. I will ask around to see if we can improve this time. I agree it would be good to have again.

I've skimmed the docs of `h5serv`. We could try to run `h5serv` on CI. But honestly, I've no idea how complicated this will be.

**Review by kmuehlbauer — APPROVED** [review]

**Comment by kmuehlbauer** [comment]
Adding back testing of h5pyd based data should not hold off merge here. I'll merge by tomorrow. @ajelenak would we need to cut a release soon?

**Pull request merged**
