### PR TITLE
Refactor dimension scale handling

### LINKED ISSUE #88: dimension processing performance when appending to file
As reported by @aldanor in https://github.com/pydata/xarray/issues/2857 `h5netcdf` shows performance degradation when consecutively appending groups with datasets having dimensions.

The problem is that for every append the whole file/group/subgroup structure is traversed to find unassigned dimensions, create the missing dimension scales and attach it properly to the file.

A quick check commenting the three lines of code handling the dimensions:

https://github.com/h5netcdf/h5netcdf/blob/0d6c2268fda93bd0a9e98a3e1a8e305f011df5a2/h5netcdf/core.py#L857-L863

shows, that this resolves the performance hit (but not writing any dimension scales).

A possible solution was suggested by @shoyer https://github.com/pydata/xarray/issues/2857#issuecomment-807319582:

> I suspect this could be solved by adding an optimization into h5netcdf to only call _attach_dim_scales() (and maybe some other methods) on variables/groups that have been modified (as opposed to the entire file).

Please see also discussion including extensive tests provided by @aldanor in https://github.com/pydata/xarray/issues/2857.

### PR DESCRIPTION
**Pull request by kmuehlbauer**
This PullRequest refactors the dimension scale handling from creating/attaching at file close to an on-the-fly creation/attaching process. This improves performance drastically (see #101 for example).

The example added builds on the nice example at the [unidata blog ](https://www.unidata.ucar.edu/blogs/developer/en/entry/netcdf4_shared_dimensions).

- builds on #104
- replaces #101 (at least partly)
- closes #88

I'll rebase when #104 is merged.

### CODE REVIEW

**Comment by kmuehlbauer** [comment]
@shoyer This one builds on #104. If #104 gets merged, I can rebase here. Or we can decide to skip #104 and merge this one instead.

**Comment by kmuehlbauer** [comment]
@shoyer This is ready for review, too.

**Comment by kmuehlbauer** [comment]
Latest perormance check with the code provided by @aldanor:

```python
import time
import xarray as xr
import numpy as np
import h5py

arr = xr.DataArray(np.random.RandomState(0).randint(-100, 100, (50_000, 3)), dims=['x', 'y'])
ds = xr.Dataset({'arr': arr})

filename = 'test.h5'
save = lambda group: ds.to_netcdf(filename, engine='h5netcdf', mode='a', group=str(group))

with h5py.File(filename, 'w') as _:
    pass

for i in range(100):
    save(i)
```
|  netcdf4    |  h5netcdf 0.12.0  |  h5netcdf-refactor |
|-----|------|-----|
| 2.6 sec   | 21.2 sec | 3.6 sec |

**Review by shoyer — APPROVED** [review]

**Comment by kmuehlbauer** [comment]
Let's merge #104 first and rebase here. It might make regression detection easier (not hoping there will be any).

**Pull request merged**
