### PR TITLE
Support wrapping an h5py File object

### PR DESCRIPTION
**Pull request by takluyver**
- [x] Closes Issue #237
- [x] Tests added
- [x] Changes are documented in `CHANGELOG.rst`

### CODE REVIEW

**Comment by takluyver** [comment]
I just remembered to add it to the docstring. I think from my side it's all ready to go now. :slightly_smiling_face:

**Comment by kmuehlbauer** [comment]
Thanks a bunch @takluyver. I'll see to get a release out in the next days.

**Comment by takluyver** [comment]
Thank you!

**Comment by kmuehlbauer** [comment]
@takluyver Sorry, this took some more time, but finally 1.4.0 is out.

**Comment by takluyver** [comment]
Thanks! :tada:

**Pull request merged**
