### PR TITLE
Switch warning into error when using invalid netCDF features

### LINKED ISSUE #100: Switch using invalid netCDF features from a warning into an error?
We added a warning when writing invalid netCDF files back in 2017:
https://github.com/h5netcdf/h5netcdf/pull/29

This was intended as an incremental step to preserve backwards compatibility. At this point, it would _probably_ be better to switch h5netcdf to raise an error in these cases instead. Or if we don't actually want to make that change, we should remove the note about the warning turning into an error changing in the future :)

### PR DESCRIPTION
**Pull request by kmuehlbauer**
Resolves #100

### CODE REVIEW

**Comment by kmuehlbauer** [comment]
Updated `README.rst` and removed stale comments. Should be ready for review.

**Comment by kmuehlbauer** [comment]
@shoyer I'll rebase this when #108 and #109 are in, but you might have a look already.

**Comment by kmuehlbauer** [comment]
I've rebased on latest master, @shoyer. This is ready for review.

**Review by shoyer — APPROVED** [review]
I wonder, would this be a good time to also declare version 1.0?

**Pull request merged**
