### PR TITLE
Fix complex and hdf5=1.10 tests

### PR DESCRIPTION
**Pull request by kmuehlbauer**
- [x] Closes Issue #243, #236 
- [x] Tests fixed
- [x] Changes are documented in `CHANGELOG.rst`

### CODE REVIEW

**Comment by kmuehlbauer** [comment]
@drew-parsons I've managed to setup a CI including hdf5 1.10.6 and h5py 3.11. I've enabled pytest.raises to catch both exceptions. Appreciate, if you could check this on your end. 

I'd merge and do a patch release, if everything is good on your side.

**Comment by drew-parsons** [comment]
Looks good.

Builds successfully https://buildd.debian.org/status/package.php?p=python-h5netcdf
Passes tests (1.4.0-3)  https://ci.debian.net/packages/p/python-h5netcdf/

**Comment by drew-parsons** [comment]
I should clarify, some tests are failing in debian unstable at https://ci.debian.net/packages/p/python-h5netcdf/

But all tests are passing in debian testing,
currently marked with green ticks on https://tracker.debian.org/pkg/python-h5netcdf

For the purpose of this patch successful tests in testing are sufficient for thumbs up.

The failure in debian unstable is interference from other packages (looks like there is a problem with h5py that I'll need to fix).

**Comment by kmuehlbauer** [comment]
@drew-parsons 1.4.1 is out on PyPI. :rocket:

**Comment by bnlawrence** [comment]
Thanks both. I wasn't equipped to chase this down properly, so I'm glad you both stayed with it.

**Pull request merged**
