### PR TITLE
Prepare for inclusion of driver_kwds in xarray

### PR DESCRIPTION
**Pull request by zequihg50**
Prepare for the inclusion of `driver_kwds` in [xarray](https://github.com/pydata/xarray/pull/8360#discussion_r1387568762).

- [X] Tests added
- [] Changes are documented in `CHANGELOG.rst`

### CODE REVIEW

**Comment by zequihg50** [comment]
I'm not sure if `driver_kwds` is going to work in xarray due to [CachingFileManager](https://github.com/pydata/xarray/blob/e5d163a8ddef4e8aa95a2841505a642f8ffbcea6/xarray/backends/h5netcdf_.py#L174) and `driver_kwds` not being hashable, maybe it is better to unpack the `driver_kwds` in multiple parameters.

**Comment by kmuehlbauer** [comment]
> I'm not sure if `driver_kwds` is going to work in xarray due to [CachingFileManager](https://github.com/pydata/xarray/blob/e5d163a8ddef4e8aa95a2841505a642f8ffbcea6/xarray/backends/h5netcdf_.py#L174) and `driver_kwds` not being hashable, maybe it is better to unpack the `driver_kwds` in multiple parameters.

@zequihg50 I completely agree, we should just use the keywords which h5py is expecting. Then we can do unpacking `driver_kwds` over at xarray and just feed this here via `kwargs` without having to handle them here.

Then we do not have to handle prepare anything here, right?

**Comment by zequihg50** [comment]
Ok, I see. Then there is nothing to add here. I will keep this open just in case but I will close after all is merged in xarray.

**Comment by zequihg50** [comment]
Closing, no need for this, see https://github.com/pydata/xarray/pull/8360.

**Pull request closed without merging**
