### PR TITLE
Add simple test to ensure that the shape is stored in the coordinates

### PR DESCRIPTION
**Pull request by hmaarrfk**
- [ ] Closes Issue #xxxx
- [ ] Tests added
- [ ] Changes are documented in `CHANGELOG.rst`

### CODE REVIEW

**Comment by hmaarrfk** [comment]
Ultimately, there was already a test that would fail if you tried to cache things. I think this one is more straightforward.

**Comment by hmaarrfk** [comment]
The first test tha tused to fail is:
```
================================================================================= FAILURES ==================================================================================
____________________________________________________________ test_writing_to_an_unlimited_dimension[testfile.nc] ____________________________________________________________

tmp_local_or_remote_netcdf = '/tmp/pytest-of-mark/pytest-242/test_writing_to_an_unlimited_d0/testfile.nc'

    def test_writing_to_an_unlimited_dimension(tmp_local_or_remote_netcdf):
        with h5netcdf.File(tmp_local_or_remote_netcdf, "w") as f:
            # Two dimensions, only one is unlimited.
            f.dimensions["x"] = None
            f.dimensions["y"] = 3
            f.dimensions["z"] = None
    
            # Cannot create it without first resizing it.
            with pytest.raises(ValueError) as e:
                f.create_variable(
                    "dummy1", data=np.array([[1, 2, 3]]), dimensions=("x", "y")
                )
                assert e.value.args[0] == "Shape tuple is incompatible with data"
    
            # Without data.
            f.create_variable("dummy1", dimensions=("x", "y"), dtype=np.int64)
            f.create_variable("dummy2", dimensions=("x", "y"), dtype=np.int64)
            f.create_variable("dummy3", dimensions=("x", "y"), dtype=np.int64)
            f.create_variable("dummyX", dimensions=("x", "y", "z"), dtype=np.int64)
            g = f.create_group("test")
            g.create_variable("dummy4", dimensions=("y", "x", "x"), dtype=np.int64)
            g.create_variable("dummy5", dimensions=("y", "y"), dtype=np.int64)
    
            assert f.variables["dummy1"].shape == (0, 3)
            assert f.variables["dummy2"].shape == (0, 3)
            assert f.variables["dummy3"].shape == (0, 3)
            assert f.variables["dummyX"].shape == (0, 3, 0)
            assert g.variables["dummy4"].shape == (3, 0, 0)
            assert g.variables["dummy5"].shape == (3, 3)
    
            # resize dimensions and all connected variables
            f.resize_dimension("x", 2)
>           assert f.variables["dummy1"].shape == (2, 3)
E           assert (0, 3) == (2, 3)
E             At index 0 diff: 0 != 2
E             Use -v to get more diff

h5netcdf/tests/test_h5netcdf.py:1057: AssertionErro
```

**Comment by kmuehlbauer** [comment]
@hmaarrfk Not sure if I get this right, but some "h5pyd" tests are known to fail, since that particular functionality is not implemented. Did you refer to those tests?

**Comment by kmuehlbauer** [comment]
Understood, I've mixed this up. The h5pyd-tests are just there for completeness, so nothing to work on that.

**Comment by hmaarrfk** [comment]
i always saw this as a nice to have. what encouraged you to move this forward?

**Comment by kmuehlbauer** [comment]
I've thought it would fit well in the test suite.

**Pull request merged**
