### PR TITLE
hsds/h5pyd pytest 

### PR DESCRIPTION
**Pull request by kmuehlbauer**
This is combination of @ajelenak's work in #162, another branch in his fork (https://github.com/ajelenak/h5netcdf/tree/h5pyd-integ) and some fixes to hopefully make this work in CI.

- [x] Closes Issue #89, #162 
- [x] Tests fixed (partly)
- [x] Changes are documented in `CHANGELOG.rst`

### CODE REVIEW

**Comment by kmuehlbauer** [comment]
@ajelenak 

Long story short: 

I've took the chance to use your fantastic work (:1st_place_medal:) in #162 and in your [`h5pyd-integ`-branch](https://github.com/ajelenak/h5netcdf/tree/h5pyd-integ). Added some fixes and a dedicated CI-run to make it work on CI.

I've circumvented most of the `h5py` low-level calls wich do not yet have a representation in `h5pyd`. We might also have to skim through the code where h5py-calls are made and decide how to work along. 

It looks like it's working on most places. There are only two errors remaining now:

```
>       raise TypeError(f'Object of type {o.__class__.__name__} '
                        f'is not JSON serializable')
E       TypeError: Object of type int32 is not JSON serializable

```

and

```
>               raise IOError(rsp.reason)
E               OSError: Expected: 48 bytes, but got: 24

```

The first indicates some problem with serialization which might be solved and the second is when trying broadcast-writes. But nevertheless this looks solvable.

**Comment by ajelenak** [comment]
Amazing! Thank you for doing this. This looks good to me. Once it gets merged I will investigate the remaining test failures.

**Comment by ajelenak** [comment]
Thank you @kmuehlbauer ! Helped a lot.

**Comment by kmuehlbauer** [comment]
The fixture-solution is really great @ajelenak and it looks like most of the functionality is already working. Nice to see HSDS/h5pyd testing working again in CI.

**Pull request merged**
